drink_ingredient_dict = {
    "sun moon lake black tea": ["black tea"],
    "pouchong green tea": ["green tea"],
    "songboling mountain tea": ["mountain tea"],
    "lugu oolong tea": ["oolong tea"],
    "tea w/ original salty cream": ["black/green/oolong tea", "salty cream"],
    "brown sugar pearl latte": ["brown sugar", "boba", "milk"],
    "brown sugar pearl milk tea": ["brown sugar", "boba", "black tea", "non dairy creamer"],
    "brown sugar pearl matcha latte": ["brown sugar", "uji matcha", "milk"],
    "traditional milk tea": ["black/green/oolong tea", "non dairy creamer"],
    "super trio traditional milk tea": ["black/green/oolong tea", "non dairy creamer", "boba", "grass jelly", "aiyu jelly"],
    "tea latte": ["fresh milk", "black/green/oolong tea"],
    "matcha latte":	["uji matcha", "milk"],
    "peach green milk tea":	["peach chunk", "milk", "green tea"],
    "avocado mango agar cooler": ["blended avocado", "fresh milk", "coconut milk", "mango chunks", "pomelo", "agar boba"],
    "mango pomelo sago cooler":	["fresh mango", "coconut milk", "pomelo", "sago"],
    "yiFang taiwan fruit tea": ["roasted ripe pineapple", "passionfruit seeds", "lime juice", "mountain tea", "orange", "apple"],
    "watermelon coconut agar cooler": ["fresh watermelon", "coconut milk", "agar boba"],
    "kumquat passionfruit tea": ["passionfruit seeds", "green tea", "kumquat", "lime slices"],
    "green plum green tea": ["green plum", "green tea"],
    "peach fruit tea": ["peach", "lime juice", "mountain tea"],
    "peach soda pop": ["peach chunk", "7 up", "lime", "mountain tea"],
    "strawberry fruit tea":	["fresh strawberries", "lime", "green tea"],
    "strawberry milk (blended)": ["blended strawberries", "fresh milk"],
    "yakult fruit tea":	["yakult", "green tea", "passionfruit/pineapple/orange"],
    "passionfruit green tea": ["passionfruit seeds", "lime juice", "green tea"],
    "pineapple green tea": ["pineapple", "green tea"],
    "wintermelon lemon tea": ["wintermelon tea", "lime juice", "lime slices"],
    "lemon mountain tea": ["mountain tea", "lime juice", "lime slices"],
    "lemon green tea": ["green tea", "lime juice", "lime slices"],
    "aiyu jelly lemon tea":	["green tea", "aiyu jelly", "lime juice", "lime slices"],
    "sugarcane mountain tea": ["fresh sugarcane juice", "mountain tea"],
    "sugarcane lemon mountain tea":	["fresh sugarcane juice", "lime slices", "lime juice", "mountain tea"],
    "fresh taro latte":	["taro chunk", "milk"],
    "fresh taro green tea latte": ["taro chunk", "milk", "green tea"],
    "sweet taro sago latte": ["blended taro paste", "milk", "sago"],
    "red bean black glutinous rice with coconut latte": ["red bean", "black glutinous rice", "coconut milk", "fresh milk"],
    "red bean sago latte": ["blended red bean", "milk", "sago"],
    "red bean match frappe with boba": ["blended uji matcha", "milk", "boba", "red bean"],
    "super trio wintermelon tea": ["wintermelon tea", "boba", "grass jelly", "sago"],
    "wintermelon tea": ["wintermelon tea"],
    "wintermelon latte": ["wintermelon", "fresh milk"],
    "grass jelly tea": ["grass jelly", "black tea"],
    "black sesame milk": ["black sesame milk", "cheese foam"],
    "thai tea": ["thai tea"]
}
drinks_dict = {
    "sun moon lake black tea": 4.25,
    "pouchong green tea": 4.25,
    "songboling mountain tea": 4.25,
    "lugu oolong tea": 4.25,
    "tea w/ original salty cream": 4.99,
    "brown sugar pearl latte": 6.25,
    "brown sugar pearl milk tea": 6.25,
    "brown sugar pearl matcha latte": 6.45,
    "traditional milk tea": 4.99,
    "super trio traditional milk tea": 5.75,
    "tea latte": 5.25,
    "matcha latte":	5.99,
    "peach green milk tea":	5.99,
    "avocado mango agar cooler": 7.49,
    "mango pomelo sago cooler":	7.75,
    "yiFang taiwan fruit tea": 5.75,
    "watermelon coconut agar cooler": 6.25,
    "kumquat passionfruit tea": 5.25,
    "green plum green tea": 4.99,
    "peach fruit tea": 5.49,
    "peach soda pop": 5.49,
    "strawberry fruit tea":	6.25,
    "strawberry milk (blended)": 6.25,
    "yakult fruit tea":	5.99,
    "passionfruit green tea": 5.25,
    "pineapple green tea": 5.25,
    "wintermelon lemon tea": 4.99,
    "lemon mountain tea": 4.99,
    "lemon green tea": 4.99,
    "aiyu jelly lemon tea":	4.99,
    "sugarcane mountain tea": 6.25,
    "sugarcane lemon mountain tea":	6.25,
    "fresh taro latte":	5.99,
    "fresh taro green tea latte": 5.99,
    "sweet taro sago latte": 6.75,
    "red bean black glutinous rice with coconut latte": 6.25,
    "red bean sago latte": 6.25,
    "red bean match frappe with boba": 6.25,
    "super trio wintermelon tea": 5.00,
    "wintermelon tea": 4.25,
    "wintermelon latte": 4.75,
    "grass jelly tea": 4.25,
    "black sesame milk": 6.25,
    "thai tea": 4.25
}

with open("base_drinks.csv", "w") as my_file:
    drinks = list(drink_ingredient_dict.keys())
    drink_id = 1
    
    for i in range(43):
        ing_Str = ''
        for j in range(len(drink_ingredient_dict[drinks[drink_id-1]])):
            ing_Str += drink_ingredient_dict[drinks[drink_id-1]][j] + ","
        my_file.write(str(drink_id) + "," + str(drinks[drink_id-1]) + "," + str(drinks_dict[drinks[drink_id-1]]) +","+ ing_Str + '\n')
        
        drink_id += 1
     