package control;

import manager_panels.Menu;
import manager_panels.OrderHistory;
import manager_panels.Ingredient;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class Manager extends javax.swing.JPanel {

    private JFrame frame;
    private FrameHandler fh;
    private int staff_id;
    private Ingredient ingredient = new Ingredient();
    private OrderHistory order_history = new OrderHistory();
    private Menu menu = new Menu();
    
    public Manager(JFrame frame, FrameHandler fh){
        
        this.frame = frame;
        this.fh = fh;

        try {
            load_manager();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void load_manager() {
        initComponents();
        ingredient.load_table();
        ingredient.load_ingredients(inventory);
        order_history.load_table();
        order_history.load_order_history(order_log);
        menu.load_table();
        menu.load_drinks(drinks_menu);
    }

    public void set_staff_id(int staff_id) {
        this.staff_id = staff_id;
    }

    public JPanel get_inventory() {
        return inventory;
    }

    public JPanel get_drinks_menu() {
        return drinks_menu;
    }

    public JPanel get_order_log() {
        return order_log;
    }

    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }

    public void setOrder_history(OrderHistory order_history) {
        this.order_history = order_history;
    }

    public OrderHistory getOrder_history() {
        return order_history;
    }

    public Ingredient getIngredient() {
        return ingredient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        inventory = new javax.swing.JPanel();
        order_log = new javax.swing.JPanel();
        drinks_menu = new javax.swing.JPanel();

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1180, 750));

        javax.swing.GroupLayout inventoryLayout = new javax.swing.GroupLayout(inventory);
        inventory.setLayout(inventoryLayout);
        inventoryLayout.setHorizontalGroup(
            inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        inventoryLayout.setVerticalGroup(
            inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Inventory", inventory);

        javax.swing.GroupLayout order_logLayout = new javax.swing.GroupLayout(order_log);
        order_log.setLayout(order_logLayout);
        order_logLayout.setHorizontalGroup(
            order_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        order_logLayout.setVerticalGroup(
            order_logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Order History", order_log);

        drinks_menu.setPreferredSize(new java.awt.Dimension(1180, 750));

        javax.swing.GroupLayout drinks_menuLayout = new javax.swing.GroupLayout(drinks_menu);
        drinks_menu.setLayout(drinks_menuLayout);
        drinks_menuLayout.setHorizontalGroup(
            drinks_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        drinks_menuLayout.setVerticalGroup(
            drinks_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Menu", drinks_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(back)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Inventory");
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        fh.actionPerformed(evt);
    }//GEN-LAST:event_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPanel drinks_menu;
    private javax.swing.JPanel inventory;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel order_log;
    // End of variables declaration//GEN-END:variables
}
