
import java.sql.*;
import java.util.*;
import javax.swing.*;

public class Redirect extends javax.swing.JPanel {

    private JFrame frame;
    private FrameHandler fh;
    private static JPanel panel;
    
    Redirect(JFrame frame, FrameHandler fh) {
        this.frame = frame;
        this.fh = fh;
        try {
            load_redirect();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void load_redirect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        server_view = new javax.swing.JButton();
        manager_view = new javax.swing.JButton();

        server_view.setText("Server View");

        manager_view.setText("Manager View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(server_view)
                .addGap(68, 68, 68)
                .addComponent(manager_view)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(server_view)
                    .addComponent(manager_view))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manager_view;
    private javax.swing.JButton server_view;
    // End of variables declaration//GEN-END:variables
}
